services:
  db:
    restart: always
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-seed:/docker-entrypoint-initdb.d
  thesketchdb:
    restart: always
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=thesketchdb.com
      - LETSENCRYPT_HOST=thesketchdb.com
    volumes:
      - ./dist:/app/dist
    depends_on:
      - db
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf/:/etc/nginx/certs
      - ./certbot/www/:/var/www/certbot/:ro
      - ./dist:/data/www:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  pgdata:
