// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type Sketch = {
  id: string;
  title: string;
  slug: string;
  uploadDate: string;
  popularity: number;
  rating: number;
};

export type Creator = {
  id: string;
  name: string;
  slug: string;
  profileImage: string;
  creationDate: string;

  createdAt: string;
  updatedAt: string;
};

export type CreatorRef = Pick<Creator, "id" | "name" | "slug" | "profileImage">;
