// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type Meta = {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
};

export type Sketch = {
  id: number;
  slug: string;
  title: string;
  url: string;
  uploadDate: string;
  thumbnailName: string;
  duration: number;
  description: string;
  creator: CreatorRef;
  episode: EpisodeRef;
  episodeStart: number;
  episodeSketchOrder: number;
  recurring: RecurringRef;
  series: SeriesRef;
  seriesPart: number;

  popularity: number;
  rating: number;

  createdAt: string;
  updatedAt: string;
};

export type CastMember = {
  id: number;
  position: number;
  actor: PersonRef;
  character: CharacterRef;
  characterName: string;
  castRole: string;
  minorRole: boolean;
  thumbnailName: string;
  profileImage: string;
};

export type CastScreenshot = {
  id: number;
  clusterNumber: number;
  imageNumber: number;
  thumbnailName: string;
  profileImage: string;
};

export type Category = {
  id: number;
  name: string;
  slug: string;

  createdAt: Date;
  updatedAt: Date;
};

export type Tag = {
  id?: number;
  name?: string;
  slug?: string;
  type?: string;
  category?: Category;
  count?: number;

  createdAt: Date;
  updatedAt: Date;
};

export type RecurringRef = {
  id: number;
  slug: string;
  title: string;
  thumbnailName: string;
};

export type SeriesRef = {
  id: number;
  slug: string;
  title: string;
  thumbnailName: string;
};

export type Creator = {
  id: number;
  slug: string;
  name: string;
  alias: string;
  url: string;
  profileImage: string;
  establishedDate: string;

  createdAt: string;
  updatedAt: string;
};

export type CreatorRef = {
  id: number;
  slug: string;
  name: string;
  profileImage: string;
};

export type Show = {
  id: number;
  name: string;
  slug: string;
  profileImage: string;
  creationDate: string;

  createdAt: string;
  updatedAt: string;
};

export type ShowRef = {
  id: number;
  slug: string;
  name: string;
  profileImg: string;
};

export type Season = {
  id: number;
  slug: string;
  show: Show;
  number: number;
  airDate: string;

  createdAt: string;
  updatedAt: string;
};

export type SeasonRef = {
  id: number;
  slug: string;
  number: number;
  show: Show;
};

export type Episode = {
  id: number;
  slug: string;
  season: Season;
  number: number;
  airDate: string;
  url: string;
  youtubeId: string;

  createdAt: string;
  updatedAt: string;
};

export type EpisodeRef = {
  id: number;
  slug: string;
  title: string;
  number: number;
  airDate: string;
  thumbnail: string;
  season: SeasonRef;
};

export type Person = {
  id: number;
  slug: string;
  first: string;
  last: string;
  alias: string;
  professions: string;
  profileImage: string;
  birthDate: string;
  description: string;
  wikiPage: string;
  iMDbID: string;
  tMDbID: string;

  createdAt: Date;
  updatedAt: Date;
};

export type PersonRef = {
  id: number;
  slug: string;
  first: string;
  last: string;
  profileImage: string;
};

export type Character = {
  id: number;
  slug: string;
  name: string;
  aliases: string;
  type: string;
  profileImage: string;
  description: string;
  portrayal: PersonRef;

  createdAt: Date;
  updatedAt: Date;
};

export type CharacterRef = {
  id: number;
  slug: string;
  name: string;
  type: string;
  profileImage: string;
};

export type TranscriptLine = {
  id: number;
  lineNumber: number;
  text: string;
  startMs: number;
  endMs: number;
};
